language: python
python:
  - "3.7"
# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install -r dev_requirements.txt
# command to run tests
script:
  - pytest --cov-report term --cov=py-chord tests/
# Upload coverage report to 'Codecov'
after_script:
  - codecov --token=cf18c9bb-92c2-4e35-a653-a3dec823c532