# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: chord.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'chord.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0b\x63hord.proto\x12\x05\x63hord\"\x1d\n\x0cStoreRequest\x12\r\n\x05value\x18\x01 \x01(\x0c\"\x1c\n\rStoreResponse\x12\x0b\n\x03key\x18\x01 \x01(\x0c\"\x19\n\nGetRequest\x12\x0b\n\x03key\x18\x01 \x01(\x0c\"\x1c\n\x0bGetResponse\x12\r\n\x05value\x18\x01 \x01(\x0c\"\"\n\x14\x46indSuccessorRequest\x12\n\n\x02id\x18\x01 \x01(\x0c\"2\n\x15\x46indSuccessorResponse\x12\x19\n\x04node\x18\x01 \x01(\x0b\x32\x0b.chord.Node\" \n\x04Node\x12\n\n\x02ip\x18\x01 \x01(\t\x12\x0c\n\x04port\x18\x02 \x01(\x05\x32\xbc\x01\n\x0c\x43hordService\x12\x32\n\x05Store\x12\x13.chord.StoreRequest\x1a\x14.chord.StoreResponse\x12,\n\x03Get\x12\x11.chord.GetRequest\x1a\x12.chord.GetResponse\x12J\n\rFindSuccessor\x12\x1b.chord.FindSuccessorRequest\x1a\x1c.chord.FindSuccessorResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'chord_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_STOREREQUEST']._serialized_start=22
  _globals['_STOREREQUEST']._serialized_end=51
  _globals['_STORERESPONSE']._serialized_start=53
  _globals['_STORERESPONSE']._serialized_end=81
  _globals['_GETREQUEST']._serialized_start=83
  _globals['_GETREQUEST']._serialized_end=108
  _globals['_GETRESPONSE']._serialized_start=110
  _globals['_GETRESPONSE']._serialized_end=138
  _globals['_FINDSUCCESSORREQUEST']._serialized_start=140
  _globals['_FINDSUCCESSORREQUEST']._serialized_end=174
  _globals['_FINDSUCCESSORRESPONSE']._serialized_start=176
  _globals['_FINDSUCCESSORRESPONSE']._serialized_end=226
  _globals['_NODE']._serialized_start=228
  _globals['_NODE']._serialized_end=260
  _globals['_CHORDSERVICE']._serialized_start=263
  _globals['_CHORDSERVICE']._serialized_end=451
# @@protoc_insertion_point(module_scope)
